services:
  frontend:
    build: ./frontend
    environment:
      - VITE_API_HOST=http://localhost:7091
      - VITE_API_STREAMING=$VITE_API_STREAMING
    ports:
      - "5173:5173"
    depends_on:
      - mock-backend

  mock-backend:
    build: ./mock-backend
    ports:
      - "7091:7091"

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
