# application/vectorstore/oracle.py

import logging
import json
from typing import List, Optional, Any, Dict

from application.core.settings import settings  # :contentReference[oaicite:6]{index=6}
from application.vectorstore.base import BaseVectorStore  # :contentReference[oaicite:7]{index=7}
from application.vectorstore.document_class import Document
# We mirror the PGVector interface from pgvector.py. See that for reference. :contentReference[oaicite:8]{index=8}

logger = logging.getLogger(__name__)
logger.warning("✅ OracleVectorStore constructor called")


class OracleVectorStore(BaseVectorStore):
    def __init__(
        self,
        source_id: str = "",
        embeddings_key: str = "embeddings",
        table_name: str = "documents",
        decoded_token: Optional[str] = None,
        vector_column: str = "embedding",
        text_column: str = "text",
        metadata_column: str = "metadata",
        connection_string: str = None,
    ):
        """
        Oracle 26ai vectorstore compatible with DocsGPT BaseVectorStore contract.
        - connection_string: DSN for oracledb, e.g. "user/password@host:port/service" or a connect string.
          If not provided, reads settings.ORACLE_CONNECTION_STRING.
        """
        super().__init__()

        self._source_id = str(source_id).replace("application/indexes/", "").rstrip("/")
        self._embeddings_key = embeddings_key
        self._table_name = table_name
        self._vector_column = vector_column
        self._text_column = text_column
        self._metadata_column = metadata_column
        self._embedding = self._get_embeddings(settings.EMBEDDINGS_NAME, embeddings_key)

        # connection string via param or settings
        self._connection_string = connection_string or getattr(settings, "ORACLE_CONNECTION_STRING", None)
        if not self._connection_string:
            raise ValueError(
                "Oracle connection string is required. "
                "Set ORACLE_CONNECTION_STRING in settings or pass connection_string parameter."
            )

        try:
            import oracledb
        except ImportError:
            raise ImportError(
                "Could not import oracledb. Please install with `pip install oracledb`."
            )

        self._oracledb = oracledb
        self._connection = None
        # Create table if missing
        self._ensure_table_exists()

    def _get_connection(self):
        """Get or create oracledb connection."""
        if self._connection is None:
            # oracledb.connect accepts user/password@host:port/service or DSN parameters
            self._connection = self._oracledb.connect(self._connection_string)
            # Set autocommit off (we will commit explicitly)
            self._connection.autocommit = False
        return self._connection

    def _ensure_table_exists(self):
        """
        Create table with VECTOR column if it doesn't exist.
        Oracle does not support 'IF NOT EXISTS' in CREATE TABLE, so we try-create and ignore ORA-00955.
        """
        conn = self._get_connection()
        cursor = conn.cursor()

        logger.info("Ensuring table exists: %s", self._table_name)

        embedding_dim = getattr(self._embedding, "dimension", 768)

        create_table_sql = f"""
        CREATE TABLE {self._table_name} (
          id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
          {self._text_column} CLOB NOT NULL,
          {self._vector_column} VECTOR({embedding_dim}),
          {self._metadata_column} CLOB,
          source_id VARCHAR2(512) NOT NULL,
          created_at TIMESTAMP DEFAULT SYSTIMESTAMP
        ) TABLESPACE USERS
        """

        create_source_index_sql = f"CREATE INDEX {self._table_name}_source_id_idx ON {self._table_name}(source_id)"

        try:
            logger.info("Creating table: %s", create_table_sql)
            try:
                cursor.execute(create_table_sql)
                logger.info("Table creation attempt finished.")
            except Exception as e:
                msg = str(e).lower()
                if hasattr(e, "code") and e.code == 955:
                    logger.debug("Table already exists: %s", self._table_name)
                elif "already exists" in msg or "name is already used" in msg:
                    logger.debug("Table already exists (caught): %s", msg)
                else:
                    raise

            try:
                cursor.execute(create_source_index_sql)
            except Exception as e:
                msg = str(e).lower()
                if "already exists" in msg or ("ora-00955" in msg):
                    logger.debug("Source index already exists.")
                else:
                    logger.debug("Could not create source_id index: %s", e)

            try:
                create_vector_index_sql = f"CREATE INDEX {self._table_name}_{self._vector_column}_idx ON {self._table_name}({self._vector_column})"
                cursor.execute(create_vector_index_sql)
            except Exception as e:
                logger.debug("Skipping vector index creation or unsupported: %s", e)

            conn.commit()
        except Exception:
            conn.rollback()
            logger.exception("Failed creating Oracle vector table or index.")
            raise
        finally:
            cursor.close()

    def _serialize_metadata(self, metadata: Optional[Dict[str, Any]]) -> str:
        if metadata is None:
            return None
        try:
            return json.dumps(metadata)
        except Exception:
            # Fallback to string
            return str(metadata)

    def _deserialize_metadata(self, metadata_clob: Optional[str]) -> Dict[str, Any]:
        if not metadata_clob:
            return {}
        try:
            return json.loads(metadata_clob)
        except Exception:
            return {"raw": metadata_clob}

    def search(self, question: str, k: int = 2, *args, **kwargs) -> List[Document]:
        """
        Embed query and run VECTOR_DISTANCE similarity search in Oracle.
        Uses VECTOR_DISTANCE(column, :query_vector, 'COSINE') in ORDER BY.
        """
        query_vector = self._embedding.embed_query(question)

        conn = self._get_connection()
        cursor = conn.cursor()

        # Use an integer literal for the FETCH to avoid bind-limit issues
        try:
            search_sql = f"""
            SELECT {self._text_column}, {self._metadata_column}
            FROM {self._table_name}
            WHERE source_id = :src
            ORDER BY VECTOR_DISTANCE({self._vector_column}, :qvec, 'COSINE')
            FETCH FIRST {int(k)} ROWS ONLY
            """

            # Bind the query vector and source id.
            cursor.execute(search_sql, {"qvec": query_vector, "src": self._source_id})
            rows = cursor.fetchall()

            documents: List[Document] = []
            for text_val, metadata_val in rows:
                meta = self._deserialize_metadata(metadata_val)
                documents.append(Document(page_content=text_val, metadata=meta))

            return documents
        except Exception as e:
            logger.error("Error searching Oracle vector store: %s", e, exc_info=True)
            return []
        finally:
            cursor.close()

    def add_texts(
        self,
        texts: List[str],
        metadatas: Optional[List[Dict[str, Any]]] = None,
        *args,
        **kwargs,
    ) -> List[str]:
        """Embed texts and insert into Oracle table; returns inserted ids as strings."""
        if not texts:
            return []

        embeddings = self._embedding.embed_documents(texts)
        metadatas = metadatas or [{}] * len(texts)

        conn = self._get_connection()
        cursor = conn.cursor()

        inserted_ids: List[str] = []
        try:
            # Oracle uses RETURNING ... INTO :var for returning generated ids.
            insert_sql = f"""
            INSERT INTO {self._table_name} ({self._text_column}, {self._vector_column}, {self._metadata_column}, source_id)
            VALUES (:text, VECTOR(:vec), :meta, :src)
            RETURNING id INTO :ret_id
            """


            for text, emb, metadata in zip(texts, embeddings, metadatas):
                id_var = cursor.var(self._oracledb.NUMBER)
                meta_str = self._serialize_metadata(metadata)
            
                # Use executemany instead of execute to allow array/vector binding
                cursor.executemany(
                    insert_sql,
                    [{
                        "text": text,
                        "vec": json.dumps(emb), 
                        "meta": meta_str,
                        "src": self._source_id,
                        "ret_id": id_var,
                    }]
                )
                # get returned id
                try:
                    returned_id = id_var.getvalue()
                    # returned_id might be a Decimal or number object; coerce to str
                    inserted_ids.append(str(int(returned_id)))
                except Exception:
                    # if return not available, we can issue a fallback select but prefer returned id
                    inserted_ids.append("")
            conn.commit()
            return inserted_ids
        except Exception as e:
            conn.rollback()
            logger.exception("Error adding texts to Oracle vector store: %s", e)
            raise
        finally:
            cursor.close()

    def delete_index(self, *args, **kwargs):
        """Delete all rows for this source_id."""
        conn = self._get_connection()
        cursor = conn.cursor()
        try:
            delete_sql = f"DELETE FROM {self._table_name} WHERE source_id = :src"
            cursor.execute(delete_sql, {"src": self._source_id})
            conn.commit()
        except Exception as e:
            conn.rollback()
            logger.exception("Error deleting index in Oracle: %s", e)
            raise
        finally:
            cursor.close()

    def save_local(self, *args, **kwargs):
        """No-op for DB-backed store."""
        pass

    def get_chunks(self) -> List[Dict[str, Any]]:
        """Return all chunks for source_id as list of dicts."""
        conn = self._get_connection()
        cursor = conn.cursor()
        try:
            select_sql = f"""
            SELECT id, {self._text_column}, {self._metadata_column}
            FROM {self._table_name}
            WHERE source_id = :src
            """
            cursor.execute(select_sql, {"src": self._source_id})
            rows = cursor.fetchall()
            chunks = []
            for doc_id, text_val, metadata_val in rows:
                meta = self._deserialize_metadata(metadata_val)
                chunks.append({"doc_id": str(int(doc_id)), "text": text_val, "metadata": meta})
            return chunks
        except Exception as e:
            logger.error("Error fetching chunks from Oracle: %s", e, exc_info=True)
            return []
        finally:
            cursor.close()

    def add_chunk(self, text: str, metadata: Optional[Dict[str, Any]] = None) -> str:
        """Add a single chunk and return its id."""
        metadata = metadata or {}
        final_metadata = metadata.copy()
        final_metadata["source_id"] = self._source_id

        embeddings = self._embedding.embed_documents([text])
        if not embeddings:
            raise ValueError("Could not generate embedding for chunk")

        conn = self._get_connection()
        cursor = conn.cursor()
        try:
            insert_sql = f"""
            INSERT INTO {self._table_name} ({self._text_column}, {self._vector_column}, {self._metadata_column}, source_id)
            VALUES (:text, VECTOR(:vec), :meta, :src)
            RETURNING id INTO :ret_id
            """
            id_var = cursor.var(self._oracledb.NUMBER)
            cursor.executemany(
                insert_sql,
                [{
                    "text": text,
                    "vec": json.dumps(embeddings[0]),
                    "meta": self._serialize_metadata(final_metadata),
                    "src": self._source_id,
                    "ret_id": id_var,
                }]
            )

            conn.commit()
            returned_id = id_var.getvalue()
            return str(int(returned_id))
        except Exception as e:
            conn.rollback()
            logger.exception("Error adding chunk to Oracle: %s", e)
            raise
        finally:
            cursor.close()

    def delete_chunk(self, chunk_id: str) -> bool:
        conn = self._get_connection()
        cursor = conn.cursor()
        try:
            delete_sql = f"DELETE FROM {self._table_name} WHERE id = :id AND source_id = :src"
            cursor.execute(delete_sql, {"id": int(chunk_id), "src": self._source_id})
            deleted_count = cursor.rowcount
            conn.commit()
            return deleted_count > 0
        except Exception as e:
            conn.rollback()
            logger.exception("Error deleting chunk from Oracle: %s", e)
            return False
        finally:
            cursor.close()

    def __del__(self):
        """Close DB connection if open."""
        try:
            if hasattr(self, "_connection") and self._connection:
                try:
                    self._connection.close()
                except Exception:
                    pass
        except Exception:
            pass