#!/bin/sh
# GENERATED by scripts/export_sandbox_manifest.py from docsgpt/sandbox/manifest.py -- do not edit.
#
# Installs the sandbox's Debian packages and the pinned Node.js build (checked
# against the SHA-256 in the manifest). The Daytona snapshot runs the same commands.
set -eu
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y --no-install-recommends ca-certificates curl xz-utils fontconfig tesseract-ocr tesseract-ocr-eng poppler-utils ffmpeg libreoffice-writer-nogui libreoffice-calc-nogui libreoffice-impress-nogui chromium-headless-shell fonts-dejavu-core fonts-liberation2 fonts-crosextra-carlito fonts-crosextra-caladea fonts-noto-core fonts-noto-cjk
rm -rf /var/lib/apt/lists/*
if [ -d /usr/share/fonts/truetype/liberation ] && [ ! -e /usr/share/fonts/truetype/liberation2 ]; then ln -s liberation /usr/share/fonts/truetype/liberation2 && printf '%s\n' '<?xml version="1.0"?>' '<!DOCTYPE fontconfig SYSTEM "fonts.dtd">' '<fontconfig><selectfont><rejectfont><glob>/usr/share/fonts/truetype/liberation2/*</glob></rejectfont></selectfont></fontconfig>' > /etc/fonts/conf.d/99-docsgpt-liberation2-link.conf; fi
fc-cache -f
arch="$(dpkg --print-architecture)"
case "$arch" in amd64) node_url="https://nodejs.org/dist/v24.21.0/node-v24.21.0-linux-x64.tar.xz"; node_sha="fd8e59d5a511510f6a298afb548f18c7d2b1be404d8b4a27d94fbe49f56cb2d6";; arm64) node_url="https://nodejs.org/dist/v24.21.0/node-v24.21.0-linux-arm64.tar.xz"; node_sha="6ad1325edbdb5649c379b75a237147a666c95d4f9ae8d340fef2d1575d289ad2";; *) echo "no Node.js build pinned for $arch" >&2; exit 1;; esac
curl -fsSL --retry 3 -o /tmp/node.tar.xz "$node_url"
echo "$node_sha  /tmp/node.tar.xz" | sha256sum -c -
tar -xJf /tmp/node.tar.xz -C /usr/local --strip-components=1 --no-same-owner
rm -f /tmp/node.tar.xz /usr/local/CHANGELOG.md /usr/local/README.md
mkdir -p /usr/local/share/doc/node
mv /usr/local/LICENSE /usr/local/share/doc/node/LICENSE
node --version
npm --version
