extends: spelling
level: warning
message: "Did you really mean '%s'?"
ignore:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/coverage/**"
  - "**/public/**"
  - "**/static/**"
vocab: DocsGPT