name: "ðŸ› Bug Report"
description: "Submit a bug report to help us improve"
title: "ðŸ› Bug Report: "
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: We value your time and your efforts to submit this bug report is appreciated. ðŸ™
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "ðŸ“œ Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "It bugs out when ..."
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: "ðŸ‘Ÿ Reproduction steps"
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: "1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error"
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: "ðŸ‘ Expected behavior"
      description: "What did you think should happen?"
      placeholder: "It should ..."
  - type: textarea
    id: actual-behavior
    validations:
      required: true
    attributes:
      label: "ðŸ‘Ž Actual Behavior with Screenshots"
      description: "What did actually happen? Add screenshots, if applicable."
      placeholder: "It actually ..."
  - type: dropdown
    id: operating-system
    attributes:
      label: "ðŸ’» Operating system"
      description: "What OS is your app running on?"
      options:
        - Linux
        - MacOS
        - Windows
        - Something else
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Something else

  - type: input
    id: node-version
    validations:
      required: true
    attributes:
      label: "ðŸ¤– Node Version"
      description: >
        What Node version are you using?
  - type: textarea
    id: additional-context
    validations:
      required: false
    attributes:
      label: "ðŸ“ƒ Provide any additional context for the Bug."
      description: "Add any other context about the problem here."
      placeholder: "It actually ..."
  - type: textarea
    id: logs
    validations:
      required: false
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "ðŸ‘€ Have you spent some time to check if this bug has been raised before?"
      options:
        - label: "I checked and didn't find similar issue"
          required: true
  - type: dropdown
    attributes:
      label: Are you willing to submit PR?
      description:
        This is absolutely not required, but we are happy to guide you in the contribution process.
        - "Yes I am willing to submit a PR!"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
