export const AUDIO_FILE_ACCEPT: Record<string, string[]> = {
  'audio/mpeg': ['.mp3'],
  'audio/mp4': ['.m4a'],
  'audio/ogg': ['.ogg'],
  'audio/wav': ['.wav'],
  'audio/webm': ['.webm'],
  'video/webm': ['.webm'],
};

export const FILE_UPLOAD_ACCEPT: Record<string, string[]> = {
  'application/pdf': ['.pdf'],
  'text/plain': ['.txt'],
  'text/x-rst': ['.rst'],
  'text/x-markdown': ['.md'],
  'application/zip': ['.zip'],
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': [
    '.docx',
  ],
  'application/json': ['.json'],
  'text/csv': ['.csv'],
  'text/html': ['.html'],
  'application/epub+zip': ['.epub'],
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': [
    '.xlsx',
  ],
  'application/vnd.openxmlformats-officedocument.presentationml.presentation': [
    '.pptx',
  ],
  'application/xhtml+xml': ['.xhtml'],
  'application/msword': ['.doc'],
  'application/vnd.ms-word.document.macroEnabled.12': ['.docm'],
  'application/vnd.oasis.opendocument.text': ['.odt'],
  'application/rtf': ['.rtf'],
  'text/rtf': ['.rtf'],
  'application/vnd.ms-powerpoint': ['.ppt', '.pps', '.pot'],
  'application/vnd.ms-powerpoint.presentation.macroEnabled.12': ['.pptm'],
  'application/vnd.openxmlformats-officedocument.presentationml.slideshow': [
    '.ppsx',
  ],
  'application/vnd.ms-powerpoint.slideshow.macroEnabled.12': ['.ppsm'],
  'application/vnd.oasis.opendocument.presentation': ['.odp'],
  'application/vnd.ms-excel': ['.xls'],
  'application/vnd.ms-excel.sheet.macroEnabled.12': ['.xlsm'],
  'application/vnd.ms-excel.sheet.binary.macroEnabled.12': ['.xlsb'],
  'application/vnd.oasis.opendocument.spreadsheet': ['.ods'],
  'image/png': ['.png'],
  'image/jpeg': ['.jpeg'],
  'image/jpg': ['.jpg'],
  ...AUDIO_FILE_ACCEPT,
};

export const FILE_UPLOAD_ACCEPT_ATTR = [
  '.pdf',
  '.txt',
  '.rst',
  '.md',
  '.zip',
  '.docx',
  '.json',
  '.csv',
  '.html',
  '.epub',
  '.xlsx',
  '.pptx',
  '.xhtml',
  '.doc',
  '.docm',
  '.odt',
  '.rtf',
  '.ppt',
  '.pptm',
  '.pps',
  '.ppsx',
  '.ppsm',
  '.pot',
  '.odp',
  '.xls',
  '.xlsm',
  '.xlsb',
  '.ods',
  '.png',
  '.jpeg',
  '.jpg',
  '.wav',
  '.mp3',
  '.m4a',
  '.ogg',
  '.webm',
].join(',');

export const AUDIO_FILE_ACCEPT_ATTR = [
  '.wav',
  '.mp3',
  '.m4a',
  '.ogg',
  '.webm',
].join(',');

export const SOURCE_FILE_TREE_ACCEPT_ATTR = [
  '.rst',
  '.md',
  '.pdf',
  '.txt',
  '.docx',
  '.csv',
  '.epub',
  '.html',
  '.mdx',
  '.json',
  '.xlsx',
  '.pptx',
  '.xhtml',
  '.doc',
  '.docm',
  '.odt',
  '.rtf',
  '.ppt',
  '.pptm',
  '.pps',
  '.ppsx',
  '.ppsm',
  '.pot',
  '.odp',
  '.xls',
  '.xlsm',
  '.xlsb',
  '.ods',
  '.png',
  '.jpg',
  '.jpeg',
].join(',');
