"""
Unit tests for the internal utility functions of the live Speech-to-Text (STT) session logic.
These tests ensure that text normalization, word splitting, prefix matching, and overlap
calculations function correctly to stabilize live transcription output.
"""

import pytest

from docsgpt.stt.live_session import (
    _calculate_commit_count,
    _common_prefix_length,
    _find_suffix_prefix_overlap,
    _normalize_word,
    _split_words,
)

# _normalize_word


def test_normalize_word_basic_lowercase():
    """Tests that standard text is simply converted to lowercase."""
    assert _normalize_word("Hello") == "hello"


def test_normalize_word_removes_special_characters():
    """Tests that punctuation and special characters are stripped from words."""
    assert _normalize_word("Hello!!!") == "hello"


def test_normalize_word_keeps_alphanumeric():
    """Tests that numbers mixed with text are preserved during normalization."""
    assert _normalize_word("Hello123") == "hello123"


def test_normalize_word_mixed_case_and_symbols():
    """Tests a complex string containing mixed cases, text, numbers, and symbols."""
    assert _normalize_word("HeLLo@#123") == "hello123"


def test_normalize_word_only_symbols_fallback():
    """
    Tests the fallback behavior when a word is entirely symbols.

    If stripping symbols leaves an empty string, it should fall back
    to simply casefolding the original string so information isn't lost.
    """
    # When everything is removed, fallback to casefold
    assert _normalize_word("!!!") == "!!!".casefold()


# _split_words


def test_split_words_basic():
    """Tests basic splitting of a typical sentence into a list of words."""
    assert _split_words("hello world") == ["hello", "world"]


def test_split_words_extra_spaces():
    """Tests that multiple contiguous spaces do not result in empty string elements."""
    assert _split_words("  hello   world  ") == ["hello", "world"]


def test_split_words_tabs_and_newlines():
    """Tests that tabs and newline characters are treated as standard word separators."""
    assert _split_words("hello\t\nworld") == ["hello", "world"]


def test_split_words_empty_string():
    """Tests that an empty string returns an empty list instead of ['']."""
    assert _split_words("") == []


def test_split_words_only_spaces():
    """Tests that a string composed entirely of whitespace returns an empty list."""
    assert _split_words("     ") == []


# _common_prefix_length


def test_common_prefix_full_match():
    """Tests that identical word lists return a prefix length equal to their total length."""
    left = ["hello", "world"]
    right = ["hello", "world"]
    assert _common_prefix_length(left, right) == 2


def test_common_prefix_partial_match():
    """Tests that the function accurately identifies the length of a matching start."""
    left = ["hello", "world"]
    right = ["hello", "there"]
    assert _common_prefix_length(left, right) == 1


def test_common_prefix_no_match():
    """Tests that lists with completely different starting words return 0."""
    left = ["hi"]
    right = ["bye"]
    assert _common_prefix_length(left, right) == 0


def test_common_prefix_case_insensitive():
    """Tests that prefix matching correctly ignores case differences."""
    left = ["Hello"]
    right = ["hello"]
    assert _common_prefix_length(left, right) == 1


def test_common_prefix_with_special_characters():
    """Tests that prefix matching ignores punctuation anomalies generated by STT."""
    left = ["hello!!!"]
    right = ["hello"]
    assert _common_prefix_length(left, right) == 1


def test_common_prefix_empty_lists():
    """Tests that comparing with one or more empty lists safely returns 0."""
    assert _common_prefix_length([], ["hello"]) == 0
    assert _common_prefix_length(["hello"], []) == 0


# _find_suffix_prefix_overlap


def test_overlap_single_word():
    """Tests detection of a 1-word overlap between the end of the left list and start of the right."""
    left = ["i", "love", "python"]
    right = ["python", "is", "great"]
    assert _find_suffix_prefix_overlap(left, right, 1) == 1


def test_overlap_multiple_words():
    """Tests detection of multi-word overlaps across the boundary of two lists."""
    left = ["i", "love", "machine", "learning"]
    right = ["machine", "learning", "is", "cool"]
    assert _find_suffix_prefix_overlap(left, right, 2) == 2


def test_overlap_no_match():
    """Tests that distinct lists with no boundary overlap return 0."""
    left = ["hello"]
    right = ["world"]
    assert _find_suffix_prefix_overlap(left, right, 1) == 0


def test_overlap_respects_minimum_threshold():
    """Tests that an overlap shorter than the minimum is ignored even when a shorter one exists."""
    left = ["x", "a", "b", "c"]
    right = ["c", "y"]
    assert _find_suffix_prefix_overlap(left, right, 1) == 1
    assert _find_suffix_prefix_overlap(left, right, 2) == 0


def test_overlap_full_match():
    """Tests that identical lists identify an overlap equal to their entire length."""
    left = ["a", "b", "c"]
    right = ["a", "b", "c"]
    assert _find_suffix_prefix_overlap(left, right, 1) == 3


def test_overlap_case_and_symbol_insensitive():
    """Tests that overlap detection utilizes normalization to ignore punctuation and casing."""
    left = ["hello!!!"]
    right = ["hello"]
    assert _find_suffix_prefix_overlap(left, right, 1) == 1


# _calculate_commit_count

TEN_WORDS = "one two three four five six seven eight nine ten"


@pytest.mark.parametrize(
    "previous, current, is_silence, expected",
    [
        # Silence with no previous hypothesis commits all but the 2-word silence tail.
        pytest.param("", TEN_WORDS, True, 8, id="silence-no-previous"),
        # A changed first word leaves no stable prefix, so nothing commits even on silence.
        pytest.param("hello " + TEN_WORDS, "bye " + TEN_WORDS, True, 0, id="no-stable-prefix"),
        # Stable prefix of 8, but the 8-word tail of a 10-word hypothesis is held back.
        pytest.param("one two three four five six seven eight", TEN_WORDS, False, 2, id="tail-holds-back"),
        # Silence shrinks the tail to 2, so the whole stable prefix of 8 commits.
        pytest.param("one two three four five six seven eight", TEN_WORDS, True, 8, id="silence-shrinks-tail"),
        # The tail would allow 9 words, but only the 3-word stable prefix commits.
        pytest.param(
            "one two three four five",
            "one two three for five six seven eight nine ten eleven",
            True,
            3,
            id="prefix-limits",
        ),
    ],
)
def test_calculate_commit_count(previous, current, is_silence, expected):
    """Tests that the commit count is the stable prefix capped by the mutable tail."""
    assert _calculate_commit_count(previous, current, is_silence=is_silence) == expected
